language: node_js
node_js:
  - 12.16.1
cache: npm

# before_install:
install:
  - npm ci

# before_script:
script:
  - npm test
  - npm run build
  - touch .nojekyll
# after_success:
# after_faliure:
# after_script:
# before_deploy:
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  local_dir: dist
  on:
    branch: develop
# after_deploy:
